blog/blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth
from django.urls import include
from django.urls import path
from django.conf import settings

from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blogapp.urls')),
    path('user/', include('accounts.urls')),
    path('', views.index, name='index'),
    path("login/", auth.LoginView.as_view(), name='login'),
    path("logout/", auth.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    path("reset-password/", auth.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_reset'),
    path("reset-password_done/",
         auth.PasswordChangeDoneView.as_view(template_name='registration/reset-password-done.html'),
         name='password_change_done'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blogapp/urls.py
from django.urls import path

from .views import ArticleCreateView
from .views import ArticleDeleteView
from .views import ArticleDetailView
from .views import ArticleListView
from .views import ArticleUpdateView
from .views import download_article

app_name = 'blogapp'

urlpatterns = [
    path("", ArticleListView.as_view(), name='article-list'),
    path("<int:id>/", ArticleDetailView.as_view(), name='article-details'),
    path("create/", ArticleCreateView.as_view(), name='article-create'),
    path("<int:id>/update/", ArticleUpdateView.as_view(), name='article-update'),
    path("<int:id>/delete/", ArticleDeleteView.as_view(), name='article-delete'),
    path('download/<int:article_id>/', download_article, name="download")

]

blog/blogapp/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models

from blogapp.utils import article_extra_image_location
from blogapp.utils import article_image_location


class Article(models.Model):
    title = models.CharField(max_length=120)
    content = models.TextField()
    active = models.BooleanField(default=True)
    top_image = models.ImageField(upload_to=article_image_location)
    added_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return "/blog/%s" % self.id

    def __str__(self):
        return self.title


class ArticleImage(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, default=None)
    image = models.ImageField(upload_to=article_extra_image_location)

blog/blogapp/forms.py
from django import forms

from blogapp.models import Article, ArticleImage


class ArticleForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Title',
        }
    ))
    content = forms.CharField(widget=forms.Textarea(
        attrs={
            'placeholder': 'Content',
        }
    ))

    class Meta:
        model = Article
        fields = {
            'title',
            'content',
            'active',
            'top_image'
        }
        widgets = {
            'title': forms.TextInput,
            'content': forms.Textarea,
        }


class ArticleImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')

    class Meta:
        model = ArticleImage
        fields = ('image',)

blog/blogapp/views.py
from logging import getLogger

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelformset_factory
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import DeleteView
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.views.generic.base import View

from comment.forms import CommentForm
from comment.models import Comment
from .forms import ArticleForm
from .forms import ArticleImageForm
from .models import Article
from .models import ArticleImage

logger = getLogger('blogapp.views')


class ArticleObjectMixin(object):
    model = Article

    def get_object(self, queryset=None):
        pk = self.kwargs.get("id")
        logger.info("article id: {}".format(pk))

        return get_object_or_404(self.model, id=pk)


class ArticleCreateView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    def post(self, request):

        ImageFormSet = modelformset_factory(ArticleImage,
                                            form=ArticleImageForm, extra=3)

        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES)
            formset = ImageFormSet(request.POST, request.FILES,
                                   queryset=ArticleImage.objects.none())

            if form.is_valid() and formset.is_valid():
                post_form = form.save(commit=False)
                post_form.user = request.user
                post_form.added_by = request.user
                post_form.save()
                logger.info("new article id {} created by {}".format(post_form.id, request.user))

                for form in formset.cleaned_data:
                    image = form['image']
                    photo = ArticleImage(article=post_form, image=image)
                    photo.save()
                messages.success(request, "Posted!")
                return HttpResponseRedirect("/")
            else:
                print(form.errors, formset.errors)
        else:
            form = ArticleForm()
            formset = ImageFormSet(queryset=ArticleImage.objects.none())
        return render(request, 'blogapp/article_create.html',
                      {'form': form, 'formset': formset})

    def get(self, request):

        ImageFormSet = modelformset_factory(ArticleImage, form=ArticleImageForm, extra=3)
        form = ArticleForm()
        formset = ImageFormSet(queryset=ArticleImage.objects.none())
        return render(request, 'blogapp/article_create.html',
                      {'form': form, 'formset': formset})


class ArticleListView(ListView):
    queryset = Article.objects.all().order_by('-id')


class ArticleDetailView(ArticleObjectMixin, View):
    template_name = "blogapp/article_detail.html"
    context = dict()

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj is not None:
            form = CommentForm(request.POST or None)
            self.context['form'] = form
            self.context['object'] = obj
            c = Comment.objects.filter(article=obj).order_by('-id')
            carousel = ArticleImage.objects.filter(article=obj)

            self.context['comments'] = c
            self.context['carousel'] = carousel
        logger.info("article {} viewed".format(obj))

        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj is not None:
            form = CommentForm(request.POST or None)
            if form.is_valid():
                s = form.save(commit=False)
                s.article = obj

                try:
                    s.added_by = request.user
                    logger.info("article {} commented by {}".format(obj, s.added_by))

                except Exception as e:
                    logger.warning("{}".format(e))
                    logger.info("login called")
                    return redirect('login')

                s.save()
                return HttpResponseRedirect(f'/blog/{obj.id}')
            c = Comment.objects.filter(article=obj).order_by('-id')
            self.context['object'] = obj
            self.context['comments'] = c
            self.context['form'] = form

        return render(request, self.template_name, self.context)


class ArticleUpdateView(UpdateView):
    form_class = ArticleForm
    template_name = 'blogapp/article_create.html'

    def get_object(self, queryset=None):
        pk = self.kwargs.get("id")
        return get_object_or_404(Article, id=pk)

    def get_success_url(self):
        success_url = "/blog/"
        return success_url


class ArticleDeleteView(DeleteView):
    success_url = "/blog/"

    def get_object(self, queryset=None):
        pk = self.kwargs.get("id")
        return get_object_or_404(Article, id=pk)


def download_article(request, article_id):
    from .pdf import pdf_view
    try:
        article = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        return HttpResponse("Article Does Not exist")
    response = pdf_view(request, article)
    return response

blog/blogapp/templates/blogapp/article_confirm_delete.html
<form action="." method="POST">
    {% csrf_token %}
    <h1>Do you want to delete this blog "{{ object.title }}"?</h1>
    <p><input type="submit" value="Yes"/> <a href="../">Cancel</a></p>
</form>

blog/blogapp/templates/blogapp/article_create.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2>Create Blog</h2>
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                {{ form.errors }}
                {{ form.title }}
                Active: {{ form.active }}
                {{ form.content }}
                {{ form.top_image }}
            </div>
            {{ formset.management_form }}
            {% for form in formset %}
                {{ form }}
            {% endfor %}
            <div>
                <button class="btn btn-primary" type="submit">Create</button>

            </div>
        </form>
    </div>
{% endblock %}

blog/blogapp/templates/blogapp/article_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <a href="{% url 'blogapp:download'  object.id %}">
            <button class="btn btn-primary">
                Download PDF
            </button>
        </a>
        <div class="card m-2">
            <div class="card-header">
                <h1 class="card-title"><b>{{ object.title | title }}</b></h1>
            </div>
            <img src="{{ object.top_image.url }}" class="card-img-top " alt="{{ object.title }} image">
            <div class="card-body">
                <p class="card-text">{{ object.content }}</p>
            </div>
            <div>
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form.comment }}
                    <button class="btn btn-primary" type="submit">Submit</button>
                </form>
            </div>
            <div class="col-md-12 col-sm-12 rounded" id="employee_table">
                <div class="row comments">
                    <div class="comment col-12 rounded ">
                        {% for comment in comments %}
                            <p class="pull-right">
                                <a href="{{ edit_url }}"><i class="fas fa-edit"></i></a>
                            </p>
                            <strong><a href="#"><b>{{ comment.added_by.username }}</b>
                                <small>{{ comment.added_on |timesince }} ago</small></a></strong>
                            <p class=" text-dark">{{ comment.comment }}</p>
                            <hr>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block extra-js %}
        <script>
            function autoReload() {
                setTimeout(function () {
                    $.ajax({
                        url: '/blogapp/article_detail.html',
                        success: function (data) {
                            document.getElementById("employee_table").innerHTML = data;
                        }
                    });
                    autoReload();  // calling again after 5 seconds
                }, 5000);
            }

            autoReload();
        </script>

    {% endblock %}
{% endblock %}

blog/blogapp/templates/blogapp/article_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">

            <div class="carousel-item active">
                <img src="{% static "img/c1.jpg" %}" class="d-block w-100 h-50" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static "img/c2.jpg" %}" class="d-block w-100 h-50" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static "img/c3.jpg" %}" class="d-block w-100 h-50" alt="...">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="container">
        <div class="btn-group p-1">
            <button type="button" class="btn btn-primary">
                Total Blog <span class="badge badge-light">{{ object_list | length }}</span>
            </button>
            <a href="{% url 'blogapp:article-create' %}">
                <button type="button" class="btn btn-success">
                    Create an Article
                </button>
            </a>
        </div>
        {% for instance in object_list %}
            <div class="card m-2">
                <img style="height: 250px; width: 100%; object-fit: cover;"
                     src="{{ instance.top_image.url }}" class="card-img-top" alt="{{ instance.title }} image">

                <div class="card-body">
                    <h5 class="card-title"><b>{{ instance.title | title }} <small>by <b>{{ instance.added_by }}</b></small></b></h5>

                    <p class="card-text">{{ instance.content | capfirst | truncatechars:128 }}...
                        <a href="{{ instance.get_absolute_url }}">
                            <b>Read More...</b>
                        </a>
                    </p>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}